theme: jekyll-theme-midnight
title: "T.G.D.K.P."
description: "Team T.G.DKP site and blog."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "Chess game"
google_analytics:
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
